/**
 * Chrome browser configuration constants
 */

export const CHROME_DEFAULT_USER_AGENT = 
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36';

export const CHROME_EXTENSIONS: Record<string, any> = {}; // Coming in a separate PR
export const CHROME_EXTENSIONS_PATH = 'chrome_extensions';
export const CHROME_PROFILE_PATH = 'chrome_profile';
export const CHROME_PROFILE_USER = 'Default';
export const CHROME_DEBUG_PORT = 9222;

export const CHROME_DISABLED_COMPONENTS = [
  'Translate',
  'AcceptCHFrame',
  'OptimizationHints',
  'ProcessPerSiteUpToMainFrameThreshold',
  'InterestFeedContentSuggestions',
  'CalculateNativeWinOcclusion',
  'BackForwardCache',
  'HeavyAdPrivacyMitigations',
  'LazyFrameLoading',
  'ImprovedCookieControls',
  'PrivacySandboxSettings4',
  'AutofillServerCommunication',
  'CertificateTransparencyComponentUpdater',
  'DestroyProfileOnBrowserClose',
  'CrashReporting',
  'OverscrollHistoryNavigation',
  'InfiniteSessionRestore',
  //'LockProfileCookieDatabase', // Disabling allows multiple chrome instances to concurrently modify profile, but might make chrome much slower
];

export const CHROME_HEADLESS_ARGS = [
  '--headless=new',
  '--test-type',
  '--test-type=gpu', // https://github.com/puppeteer/puppeteer/issues/10516
  // '--enable-automation', // <- DONT USE THIS, it makes you easily detectable / blocked by cloudflare
];

export const CHROME_DOCKER_ARGS = [
  // Docker-specific options
  '--no-sandbox', // Rely on Docker sandboxing in Docker, otherwise we need cap_add: SYS_ADM to use host sandboxing
  '--disable-gpu-sandbox',
  '--disable-setuid-sandbox',
  '--disable-dev-shm-usage', // Docker 75mb default shm size is not big enough, disabling just uses /tmp instead
  '--no-xshm',
];

export const CHROME_DISABLE_SECURITY_ARGS = [
  // DANGER: JS isolation security features (to allow easier tampering with pages during automation)
  '--disable-web-security', // <- WARNING, breaks some sites that expect/enforce strict CORS headers
  '--disable-site-isolation-trials',
  '--disable-features=IsolateOrigins,site-per-process',
  // DANGER: Disable HTTPS verification
  '--allow-running-insecure-content', // Breaks CORS/CSRF/HSTS etc., useful sometimes but very easy to detect
  '--ignore-certificate-errors',
  '--ignore-ssl-errors',
  '--ignore-certificate-errors-spki-list',
  '--allow-insecure-localhost',
];

export const CHROME_DETERMINISTIC_RENDERING_ARGS = [
  '--deterministic-mode',
  '--js-flags=--random-seed=1157259159', // Make all JS random numbers deterministic by providing a seed
  '--force-device-scale-factor=1',
  '--hide-scrollbars', // Hide scrollbars because otherwise they show up in screenshots
  // GPU, canvas, text, and pdf rendering config
  '--enable-webgl', // Enable web-gl graphics support
  '--font-render-hinting=none', // Make rendering more deterministic by ignoring OS font hints
  '--force-color-profile=srgb', // Make rendering more deterministic by using consistent color profile
  '--disable-partial-raster', // Make rendering more deterministic
  '--disable-skia-runtime-opts', // Make rendering more deterministic by avoiding Skia hot path runtime optimizations
  '--disable-2d-canvas-clip-aa', // Make rendering more deterministic by disabling antialiasing on 2d canvas clips
  // Process management & performance tuning
  '--disable-lazy-loading', // Make rendering more deterministic by loading all content up-front instead of on-focus
  '--disable-renderer-backgrounding', // Don't throttle tab rendering based on focus/visibility
  '--disable-background-networking', // Don't throttle tab networking based on focus/visibility
  '--disable-background-timer-throttling', // Don't throttle tab timers based on focus/visibility
  '--disable-backgrounding-occluded-windows', // Don't throttle tab window based on focus/visibility
  '--disable-ipc-flooding-protection', // Don't throttle ipc traffic or accessing big request/response/buffer/etc. objects will fail
  '--disable-extensions-http-throttling', // Don't throttle http traffic based on runtime heuristics
  '--disable-field-trial-config', // Disable shared field trial state between browser processes
  '--disable-back-forward-cache', // Disable browsing navigation cache
];

export const CHROME_ARGS = [
  // Profile data dir setup
  '--disable-cookie-encryption', // We need to be able to write unencrypted cookies
  '--disable-sync', // Don't try to use Google account sync features while automation is active
  // Extensions
  '--allow-legacy-extension-manifests',
  '--allow-pre-commit-input', // Allow JS mutations before page rendering is complete
  '--disable-blink-features=AutomationControlled', // Hide the signatures that announce browser is being remote-controlled
  // Browser window and viewport setup
  '--install-autogenerated-theme=0,0,0', // Black border makes it easier to see which chrome window is automated
  // IO: stdin/stdout, debug port config
  '--log-level=2', // 1=DEBUG 2=WARNING 3=ERROR
  '--enable-logging=stderr',
  `--remote-debugging-port=${CHROME_DEBUG_PORT}`,
  '--enable-experimental-extension-apis', // Add support for tab groups
  '--disable-focus-on-load', // Prevent browser from hijacking focus
  '--disable-window-activation',
  // Output format options (PDF, screenshot, etc.)
  '--export-tagged-pdf', // Include table of contents and tags in printed PDFs
  '--generate-pdf-document-outline',
  // Suppress first-run features, popups, hints, updates, etc.
  '--no-pings',
  '--no-first-run',
  '--no-default-browser-check',
  '--no-startup-window',
  '--disable-default-apps',
  '--ash-no-nudges',
  '--disable-infobars',
  '--disable-search-engine-choice-screen',
  '--disable-session-crashed-bubble',
  '--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"', // Disable browser self-update while automation is active
  '--hide-crash-restore-bubble',
  '--suppress-message-center-popups',
  '--disable-client-side-phishing-detection',
  '--disable-domain-reliability',
  '--disable-component-update',
  '--disable-datasaver-prompt',
  '--disable-hang-monitor',
  '--disable-session-crashed-bubble',
  '--disable-speech-synthesis-api',
  '--disable-speech-api',
  '--disable-print-preview',
  '--safebrowsing-disable-auto-update',
  '--deny-permission-prompts',
  '--disable-external-intent-requests',
  '--disable-notifications',
  '--disable-desktop-notifications',
  '--noerrdialogs',
  '--disable-popup-blocking',
  '--disable-prompt-on-repost',
  '--silent-debugger-extension-api',
  '--block-new-web-contents',
  '--metrics-recording-only',
  '--disable-breakpad',
  // Other feature flags
  `--disable-features=${CHROME_DISABLED_COMPONENTS.join(',')}`,
  '--enable-features=NetworkService',
]; 